export const recipes = [
  {
    title: "Svamp stroganoff med ris",
    ingridients: [
      "2 stora gula lökar",
      "3 klyftor vitlök",
      "600 g svamp (t.ex. skogschampinjoner eller champinjoner)",
      "1 burk kokosgrädde (à 400 ml)",
      "0,5 dl vatten",
      "3 msk tomatpuré",
      "3 msk dijonsenap",
      "3 msk tamarisoja (eller annan soja)",
      "2 msk olivolja, till stekning",
      "Svartpeppar",
    ],
    howto: [
      "Börja koka råriset, se anvisningarna på förpackningen.",
      "Skiva gul lök och finhacka vitlöken.",
      "Skiva svampen i ca 5 mm tjocka skivor.",
      "Värm stekpannan och häll i olivolja.",
      "Stek lök och svamp på mellanvärme i ca 10 minuter tills lök och svamp är gyllenbruna. Rör om ofta.",
      "Tillsätt vitlöken och fräs ytterligare ca 1 minut.",
      "Tillsätt kokosgrädden i stekpannan. Häll vattnet i burken, skaka om och häll i pannan så att du får ut allt ur burken.",
      "Tillsätt tomatpuré, dijonsenap och tamari. Om du använder annan soja än tamari så börja med en mindre mängd och smaka av hur mycket som behövs. Låt puttra i ca 5 minuter. Smaka av med svartpeppar.",
      "Ånga broccolin under tiden stroganoffen puttrar. Skär broccolihuvudet i lagom stora buketter och skiva stammen i ca 1 cm tjocka bitar. Häll ca 0,5 cm vatten i botten av en kastrull eller stekpanna och koka upp. Lägg i broccolin, lägg på ett lock och låt ånga ca 3-4 minuter.",
      "Servera stroganoffen med det kokta råriset, broccolin och hackad persilja.",
    ],
    image: "https://i.imgur.com/tjg7AGa.jpg",
  },
];
